repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.2.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
        pass_filenames: false
      # Run the formatter.
      - id: ruff-format
        pass_filenames: false
