name: release with poetry

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/textmate_grammar/__init__.py'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        
      - name: Install the project dependencies
        run: poetry install --without dev,test

      - name: configure PyPi token
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: poetry config pypi-token.pypi "$PYPI_TOKEN"

      - name: Release to PyPi
        run: poetry publish --build

      
