name: Test on main

on: 
  workflow_dispatch:
  push:
    branches:
      - main
  

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install node dependencies
        run: |
          mkdir test/nodejs/node_root
          cp test/nodejs/src/index.js test/nodejs/node_root
          cd test/nodejs/node_root
          npm init -y
          npm install oniguruma typescript vscode-oniguruma vscode-textmate

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        run: |
          pytest
